version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app/backend
    command: node server.js
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
